project_id = "oiljiebciwtjlrtqicty"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.send-invite-email]
    verify_jwt = false
  [functions.send-contact-email]
    verify_jwt = false
